name: Collect Air Quality Data

on:
  schedule:
    - cron: "0 * * * *" # Setiap jam
  workflow_dispatch: # Untuk memicu manual

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Collect air quality data
        run: python collectAuto.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update air quality data [automated]" && git push)
